### ISSUE TITLE
Normalise config options

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#10]
make all CLI options compatible with nested yaml config file, e.g.:

```
common:
  docker:
    es:
      container: ghubs-es
```

```
GenomeHubs init --docker-es-container ghubs-es ...
```
