### ISSUE TITLE
allow synonyms for attribute keys

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#153]
At present, changing an attribute key is a breaking change so allowing synonyms will provide a way to update attribute keys while offering a fallback for queries using the old names.

would be convenient to specify this in the yaml like:
```
attributes:
  bioproject:
    ...
    synonyms:
      - bioproject_accession
    type: keyword
```
