### ISSUE TITLE
Reduce log messages in some genomehubs commands

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#257]
Request to reduce the frequency of logs (eg every minute instead of second), or every 10000 records instead of every 1 or 10 or 100 records)

In all cases - nice to have log msg at start, every Nth record/row (10,000?), end

* genomehubs parse --refseq-organelles
* genomehubs init
  * fetch taxdump.tar.gz uses tolkit so I think any file fetch should be at the start and maybe after every 10MB and the end?
  * init reports every 500 records, can that be every 10000 records?
* genomehubs index
  * processing rows - i can't tell what the unit of reporting is, but could easily be every 10,000 rows
  * indexing reports every 500 records, can that be every 10000 records as well
* genomehubs fill
  * reports every 500 records, can be made 10000

One thought - the default could be 10,000 - with the option to change, or switch off completely?

**Comment by rjchallis** [comment]
Now possible to set batch size for bulk indexing, enable/disable logging and set logging frequency via command line options and in config. To set default options in config, use:
```
common:
  es:
    batch: 5000    # Number of records to send per batch for elastic search but indexing
                   # Total size of documents being indexed must not exceed 100MB
                   # Default: 500
    ...
  log:
    es: false      # Set `true` to print Info level log messages from elasticsearch functions
                   # Set `false` to only show errors
                   # Default: true
    fetch: false   # Set `true` to print Info level log messages from fetch commands
                   # Set `false` to supress all log messages from fetch commands
                   # Set `/path/to/log/file` to redirect log messages to file
                   # Default: true
    interval: 10   # Interval in seconds between log updates (only affects elastic search logs)
                   # Default: 1
  ...

```

Or use `--log-es`, `--log-interval`, etc.
