### ISSUE TITLE
Use preferred values in aggregation

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#62]
When summarising multiple values for a taxon, often one of the values can be labelled as the preferred value (e.g. `prime_value` field in Kew plant c values. 

Need a summary option to use this value if available (e.g. give column header and check if value is true or false)

**Comment by rjchallis** [comment]
Implemented using `primary` summary type and `is_primary_value` metadata column. Primary value column should be 1 (primary)/ 0 (not primary).

If the number of primary values for an taxon != 1, the second entry in the list of summary types will be used to calculate the summary value.

A limitation is that all attributes in a single yaml config will share the same `is_primary_value`

test.yaml
```
attributes:
    c_value:
        ...
        summary:
            - primary
            - mean
        ...
metadata:
    is_primary_value:
        header: prime_value
```

test.tsv
```
species	taxon_id	c_value	prime_value	family
Apus apus	8895	1.28	0	Apodidae
Strix aluco	111821	1.5	0	Strigidae
Strix aluco	111821	1.9	1	Strigidae
```
