### ISSUE TITLE
use enum position to prioritise values during traverse

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#74]
Filling values such as assembly_level requires ranking to determine which value to propagate. This ranking could be taken from the associated enum, e.g.:

```
assembly_level:
    ...
    constraint:
      enum:
        - chromosome
        - scaffold
        - contig
    summary: enum
    traverse: enum
    traverse_direction: up
    ...
```
