### ISSUE TITLE
Separate YAML for generic attribute settings

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#86]
Currently an import/index YAML is linked to an importable file. Can we have a single (or separate YAMLs) that only define attribute settings for display and indexing and filling etc?

**Comment by rjchallis** [comment]
Fix will load the first (alphabetically) YAML and read attribute settings from there even if it has no file associated. Subsequent values for the same attributes will not overwrite the stored values, but are used during individual file import. e.g.:

genomesize.0.types.yaml
```
file:
  display_group: genome_size
attributes:
  c_value:
    bins:
      min: -2.5
      max: 2.5
      count: 10
      scale: log10
    constraint:
      max: 200
      min: 0
    description: 1C value
    display_level: 1
    summary:
      - mean
      - median
      - max
      - min
    traverse: mean
    type: half_float
    units: pgDNA
```

genome size.1.types.yaml
```
file:
  format: tsv
  header: true
  name: genomesize.tsv
  source: Example Genome Size Database
  source_url: http://example.com
attributes:
  cell_type:
    header: c_value
    separator:
      - ","
taxon_names:
  common_name:
    header: common_name
taxonomy:
  taxon_id:
    header: taxon_id
  species:
    header: species
  family:
    header: family

```
