### ISSUE TITLE
Separate taxonomy format from taxonomy name

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#94]
Need flexibility to import taxonomies with different names so not tied to one taxonomy per format

**Comment by rjchallis** [comment]
Can now specify taxonomy format independently from source, e.g.:

```
genomehubs init --taxonomy-source ncbi_aves --taxonomy-format ncbi --taxonomy-root 8782 --taxonomy-file names.dmp --taxonomy-file nodes.dmp --taxonomy-url "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
```

config file should also work like:

```
taxonomy:
    ncbi_aves:
        format: ncbi
        root: 8782
        file:
            - nodes.dmp
            - names.dmp
        url: ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
```
